services:
  - type: web
    name: ai-resume-backend
    runtime: node
    plan: free
    buildCommand: cd Backend && npm install && npx prisma generate
    startCommand: cd Backend && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MAX_UPLOAD_SIZE
        value: "50mb"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
